from __future__ import annotations

from enum import Enum


class LifecycleStatus(str, Enum):
    CREATED = "CREATED"
    WAITING_TRACKING = "WAITING_TRACKING"
    BOOKED = "BOOKED"
    PICKUP_PENDING = "PICKUP_PENDING"
    PICKED_UP = "PICKED_UP"
    ORIGIN_WAREHOUSE = "ORIGIN_WAREHOUSE"
    DEPARTURE_PENDING = "DEPARTURE_PENDING"
    INTERNATIONAL_TRANSIT = "INTERNATIONAL_TRANSIT"
    ARRIVED_DESTINATION = "ARRIVED_DESTINATION"
    CUSTOMS_CLEARANCE = "CUSTOMS_CLEARANCE"
    CUSTOMS_CLEARED = "CUSTOMS_CLEARED"
    LAST_MILE_PENDING = "LAST_MILE_PENDING"
    LAST_MILE = "LAST_MILE"
    APPOINTMENT_PENDING = "APPOINTMENT_PENDING"
    APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED"
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
    DELIVERED_TO_AMAZON = "DELIVERED_TO_AMAZON"
    AMAZON_RECEIVING = "AMAZON_RECEIVING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class HealthStatus(str, Enum):
    NORMAL = "NORMAL"
    WATCH = "WATCH"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class ExceptionStatus(str, Enum):
    OPEN = "OPEN"
    FOLLOWING = "FOLLOWING"
    WAITING = "WAITING"
    RESOLVED = "RESOLVED"
    IGNORED = "IGNORED"


class ExceptionSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ResponsibleParty(str, Enum):
    FORWARDER = "FORWARDER"
    AMAZON = "AMAZON"
    INTERNAL = "INTERNAL"
    CUSTOMS = "CUSTOMS"
    UNKNOWN = "UNKNOWN"
